Airports/Models/AirportsViewModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Airports.Domain.Entities;

namespace Airports.Models
{
    public class AirportsViewModel
    {
        public AirportsViewModel(IEnumerable<string> cities)
        {
            Countries.Add(new SelectListItem { Text = "All", Value = "All" });
            Countries.AddRange(cities.Select(c => new SelectListItem { Text = c, Value = c }));
        }

        public List<Airport> Airports { get; } = new List<Airport>();

        public List<SelectListItem> Countries { get; } = new List<SelectListItem>();
    }
}

Airports/Models/DistanceViewModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Airports.Domain.ValueObjects;

namespace Airports.Models
{
    public class DistanceViewModel
    {
        public DistanceViewModel(IEnumerable<string> iataList)
        {
            IataListA.AddRange(iataList.Select(i => new SelectListItem { Text = i, Value = i }));
            IataListB.AddRange(iataList.Select(i => new SelectListItem { Text = i, Value = i }));
        }

        public Distance Distance { get; set; }

        public string Error { get; set; }

        public List<SelectListItem> IataListA { get; } = new List<SelectListItem>();

        public List<SelectListItem> IataListB { get; } = new List<SelectListItem>();
    }
}

Airports/Controllers/AirportsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Airports.Domain.QueryServices;
using Airports.Models;

namespace Airports.Controllers
{
    public class AirportsController : Controller
    {
        private readonly IAirportQueryService _airportQueryService;
        private readonly ICountryQueryService _countryQueryService;

        public AirportsController(IAirportQueryService airportQueryService, ICountryQueryService countryQueryService)
        {
            _airportQueryService = airportQueryService;
            _countryQueryService = countryQueryService;
        }

        // 2.5h
        // DropdownFor
        [HttpPost]
        public ActionResult Filter(string country)
        {
            if (country.Equals("All", StringComparison.OrdinalIgnoreCase))
            {
                country = null;
            }

            TempData["country"] = country;

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var viewModel = new AirportsViewModel(await _countryQueryService.GetAllCountriesAsync());

            if (TempData["country"] is string country)
            {
                TempData["country"] = country;
                viewModel.Airports.AddRange(await _airportQueryService.GetAllEuropeanAirportsAsyncByCountry(country));
                var filter = viewModel.Countries.FirstOrDefault(c => c.Value.Equals(country));

                if (filter != null)
                {
                    filter.Selected = true;
                }
            }
            else
            {
                viewModel.Airports.AddRange(await _airportQueryService.GetAllEuropeanAirportsAsync());
            }

            return View(viewModel);
        }
    }
}

Airports/Controllers/DistanceController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Airports.Domain.CommandHandler;
using Airports.Domain.Commands;
using Airports.Domain.QueryServices;
using Airports.Domain.ValueObjects;
using Airports.Models;

namespace Airports.Controllers
{
    public class DistanceController : Controller
    {
        private readonly IAirportQueryService _airportQueryService;
        private readonly IAirportsCommandHandler _airportsCommandHandler;

        public DistanceController(
            IAirportQueryService airportQueryService,
            IAirportsCommandHandler airportsCommandHandler)
        {
            _airportQueryService = airportQueryService;
            _airportsCommandHandler = airportsCommandHandler;
        }

        [HttpPost]
        public async Task<ActionResult> Calculate(string airportA, string airportB)
        {
            var distance = await _airportsCommandHandler.HandleAsync(
                new CalculateDistanceCommand { IataA = airportA, IataB = airportB });

            TempData["airportA"] = airportA;
            TempData["airportB"] = airportB;

            if (distance == null)
            {
                TempData["error"] = "Missing some of airport coordinates.";
            }
            else
            {
                TempData["distance"] = distance;
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var airports = await _airportQueryService.GetAllEuropeanAirportsAsync();
            var iatas = airports.Select(a => a.Iata);
            var viewModel = new DistanceViewModel(iatas);

            if (TempData["error"] is string error)
            {
                SetSelectedAirports(viewModel);
                viewModel.Error = error;
            }
            else if (TempData["distance"] is Distance distance)
            {
                SetSelectedAirports(viewModel);
                viewModel.Distance = distance;
            }

            return View(viewModel);
        }

        private void SetSelectedAirports(DistanceViewModel viewModel)
        {
            var airportA = TempData["airportA"] as string;
            var airportB = TempData["airportB"] as string;

            SetSelectedValue(viewModel.IataListA, airportA);
            SetSelectedValue(viewModel.IataListB, airportB);
        }

        private void SetSelectedValue(List<SelectListItem> selectList, string value)
        {
            var filter = selectList.FirstOrDefault(c => c.Value.Equals(value));

            if (filter != null)
            {
                filter.Selected = true;
            }
        }
    }
}

Airports/Views/Airports/Index.cshtml
@model  Airports.Models.AirportsViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Filter","Airports", FormMethod.Post))
{
    <p>
        Filter by country: @Html.DropDownList("Country", Model.Countries, new { @class = "btn" })
        <input type="submit" value="Filter" class= "btn" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.Name("Country")
        </th>
        <th>
            @Html.Name("IATA")
        </th>
        <th>
            @Html.Name("Name")
        </th>
        <th>
            @Html.Name("Size")
        </th>
        <th>
            @Html.Name("Status")
        </th>
        <th>
            @Html.Name("Coordinates")
        </th>
    </tr>

@foreach (var item in Model.Airports) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Iata)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>

            (@Html.DisplayFor(modelItem => item.Coordinates.Latitude),
            @Html.DisplayFor(modelItem => item.Coordinates.Longitude))
        </td>
    </tr>
                }
</table>

Airports/Views/Distance/Index.cshtml
@model  Airports.Models.DistanceViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Distance between airports</h2>

<div>
    <hr />

    @using (Html.BeginForm("Calculate", "Distance", FormMethod.Post))
    {
        <div class="container">
            <div class="row">
                <div class="col-sm-5">
                    <h4>Airport A</h4>
                    @Html.DropDownList("airportA", Model.IataListA, new { @class = "btn" })
                </div>
                <div class="col-sm-5">
                    <h4>Airport B</h4>
                    @Html.DropDownList("airportB", Model.IataListB, new { @class = "btn" })
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5">
                    <input type="submit" name="Calculate" class="btn btn-primary" />
                </div>
            </div>
            <div class="row">
                @if (!string.IsNullOrEmpty(Model.Error))
                {
                    <div class="alert alert-danger">
                        @Model.Error
                    </div>
                }
                @if (Model.Distance != null)
                {
                    <div class="alert alert-success">
                        <strong>Distance:</strong> @Model.Distance.Kilometers.ToString("F") km
                    </div>
                }
            </div>
        </div>
    }
</div>

Airports/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    @{
        var fromFeed = Context.Response.Headers["from-feed"];
        if (!string.IsNullOrEmpty(fromFeed))
        {
            @Html.Label(fromFeed)
        }

    }
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Airports", "Index", "Airports", new { area = string.Empty }, new { @class = "navbar-brand" })
                @Html.ActionLink("Distance", "Index", "Distance", new { area = string.Empty }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>